### ISSUE TITLE
Release Fixes to pypi

### ISSUE THREAD

**Issue by maweki** [BartMassey/pdfformread#2]
It would be nice if there were a newer pypi-release, with the recent fixes included

**Comment by BartMassey** [comment]
Not sure you're on the right issue tracker?

**Comment by maweki** [comment]
https://pypi.python.org/pypi/pdfformread

That's you, right? The pypi release does not include the newest fixes.

**Comment by BartMassey** [comment]
Oh, I see what you're saying. Yes, I'll take care of that. Thanks.

**Comment by BartMassey** [comment]
OK, I've pushed 0.1.2 to pypi. Let me know if I did it right, and I'll close this. Thanks again for reporting it!

**Comment by maweki** [comment]
Yeah, looks fine. Thank you
